-- Modelo Físico

-- ************** Conectado como usuário system **************

CREATE TABLESPACE TBS_DW
LOGGING DATAFILE '/u01/app/oracle/oradata/orcl/TBS_DW.dbf' 
SIZE 1M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE USER dw IDENTIFIED BY dw0123 DEFAULT TABLESPACE TBS_DW;
GRANT CONNECT, RESOURCE TO dw;
GRANT UNLIMITED TABLESPACE TO dw;

grant select on starea.ST_DIM_CLIENTE to dw;
grant select on starea.ST_DIM_PRODUTO to dw;
grant select on starea.ST_DIM_LOCALIDADE to dw;
grant select on starea.ST_VENDA to dw;


-- ************** Conectado como usuário dw **************

CREATE SEQUENCE dim_cliente_id_seq START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_CLIENTE 
(
  SK_CLIENTE INTEGER DEFAULT dim_cliente_id_seq.NEXTVAL, 
  NK_ID_CLIENTE VARCHAR2(20), 
  NM_CLIENTE VARCHAR2(50), 
  NM_CIDADE_CLIENTE VARCHAR2(50), 
  FLAG_ACEITA_CAMPANHA CHAR(1), 
  DESC_CEP VARCHAR2(10), 
  CONSTRAINT TB_DIM_CLIENTE_PK PRIMARY KEY (SK_CLIENTE) ENABLE 
);

CREATE SEQUENCE dim_produto_id_seq START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_PRODUTO (
    SK_PRODUTO INTEGER DEFAULT dim_produto_id_seq.NEXTVAL,
    NK_ID_PRODUTO VARCHAR(20) NOT NULL,
    DESC_SKU VARCHAR(50) NOT NULL,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR(30) NOT NULL,
    NM_MARCA_PRODUTO VARCHAR(30) NOT NULL,
    CONSTRAINT TB_DIM_PRODUTO_PK PRIMARY KEY (SK_PRODUTO) ENABLE 
);

CREATE SEQUENCE dim_localidade_id_seq START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TB_DIM_LOCALIDADE (
    SK_LOCALIDADE INTEGER DEFAULT dim_localidade_id_seq.NEXTVAL,
    NK_ID_LOCALIDADE VARCHAR(20) NOT NULL,
    NM_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR(50) NOT NULL,
    CONSTRAINT TB_DIM_LOCALIDADE_PK PRIMARY KEY (SK_LOCALIDADE) ENABLE 
);

CREATE TABLE TB_DIM_TEMPO (
    SK_DATA INTEGER NOT NULL,
    DATA DATE NOT NULL,
    NR_ANO NUMBER(4) NOT NULL,
    NR_MES NUMBER NOT NULL,
    NM_MES VARCHAR(20) NOT NULL,
    NR_DIA NUMBER NOT NULL,
    CONSTRAINT TB_DIM_DATA_PK PRIMARY KEY (SK_DATA) ENABLE 
);


CREATE TABLE TB_FATO_VENDA 
(
  SK_CLIENTE INTEGER NOT NULL, 
  SK_PRODUTO INTEGER NOT NULL, 
  SK_LOCALIDADE INTEGER NOT NULL, 
  SK_DATA INTEGER NOT NULL, 
  VL_VENDA DECIMAL(12,4), 
  QTD_VENDA INTEGER, 
  DATA_CARGA DATE,
  CONSTRAINT TB_FATO_VENDA_PK PRIMARY KEY (SK_CLIENTE, SK_PRODUTO, SK_LOCALIDADE, SK_DATA)ENABLE 
);

