-- ************** Conectado como usuário dw **************

-- Verificando Integridade

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_CLIENTE FOREIGN KEY
(
  SK_CLIENTE 
)
REFERENCES TB_DIM_CLIENTE
(
  SK_CLIENTE 
)
ENABLE;

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_DATA FOREIGN KEY
(
  SK_DATA 
)
REFERENCES TB_DIM_TEMPO
(
  SK_DATA 
)
ENABLE;

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_LOC FOREIGN KEY
(
  SK_LOCALIDADE 
)
REFERENCES TB_DIM_LOCALIDADE
(
  SK_LOCALIDADE 
)
ENABLE;

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_PRO FOREIGN KEY
(
  SK_PRODUTO 
)
REFERENCES TB_DIM_PRODUTO
(
  SK_PRODUTO 
)
ENABLE;

SELECT sum(quantidade) FROM STAREA.ST_VENDA;

SELECT
   E.NM_REGIAO_LOCALIDADE as Regiao,
   B.NM_MES as Mes,
   B.NR_ANO as Ano,
   SUM(A.QTD_VENDA) as QTD_VENDA_TOTAL,
   SUM(A.VL_VENDA) as VL_VENDA_TOTAL
 FROM TB_FATO_VENDA A
 INNER JOIN TB_DIM_TEMPO B      ON A.SK_DATA = B.SK_DATA
 INNER JOIN TB_DIM_CLIENTE C    ON A.SK_CLIENTE = C.SK_CLIENTE
 INNER JOIN TB_DIM_PRODUTO D    ON A.SK_PRODUTO = D.SK_PRODUTO
 INNER JOIN TB_DIM_LOCALIDADE E ON A.SK_LOCALIDADE = E.SK_LOCALIDADE
 GROUP BY E.NM_REGIAO_LOCALIDADE, B.NR_ANO, B.NM_MES
 ORDER BY SUM(A.VL_VENDA) DESC;

SELECT
   D.NM_PRODUTO as Produto,
   B.NM_MES as Mes,
   B.NR_ANO as Ano,
   SUM(A.QTD_VENDA) as QTD_VENDA_TOTAL,
   SUM(A.VL_VENDA) as VL_VENDA_TOTAL
 FROM TB_FATO_VENDA A
 INNER JOIN TB_DIM_TEMPO B      ON A.SK_DATA = B.SK_DATA
 INNER JOIN TB_DIM_CLIENTE C    ON A.SK_CLIENTE = C.SK_CLIENTE
 INNER JOIN TB_DIM_PRODUTO D    ON A.SK_PRODUTO = D.SK_PRODUTO
 INNER JOIN TB_DIM_LOCALIDADE E ON A.SK_LOCALIDADE = E.SK_LOCALIDADE
 GROUP BY D.NM_PRODUTO, B.NR_ANO, B.NM_MES
 ORDER BY SUM(A.VL_VENDA) DESC;

 SELECT
   E.NM_LOCALIDADE as Localidade,
   B.NM_MES as Mes,
   B.NR_ANO as Ano,
   SUM(A.QTD_VENDA) as QTD_VENDA_TOTAL,
   SUM(A.VL_VENDA) as VL_VENDA_TOTAL
 FROM TB_FATO_VENDA A
 INNER JOIN TB_DIM_TEMPO B      ON A.SK_DATA = B.SK_DATA
 INNER JOIN TB_DIM_CLIENTE C    ON A.SK_CLIENTE = C.SK_CLIENTE
 INNER JOIN TB_DIM_PRODUTO D    ON A.SK_PRODUTO = D.SK_PRODUTO
 INNER JOIN TB_DIM_LOCALIDADE E ON A.SK_LOCALIDADE = E.SK_LOCALIDADE
 GROUP BY E.NM_LOCALIDADE, B.NR_ANO, B.NM_MES
 ORDER BY SUM(A.VL_VENDA) DESC





