-- ************* Conectado como usuário dw *************

SELECT * FROM TB_DIM_PRODUTO

ALTER TABLE TB_DIM_PRODUTO ADD (PRECO_UNITARIO DECIMAL);


SELECT * FROM STAREA.ST_VENDA

BEGIN
 For i in (SELECT PRECO_UNITARIO, ID_PRODUTO FROM STAREA.ST_VENDA) 
  LOOP
   Update TB_DIM_PRODUTO set PRECO_UNITARIO = i.PRECO_UNITARIO where NK_ID_PRODUTO = i.ID_PRODUTO;
  END LOOP;
END;

COMMIT;

ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_CLIENTE DISABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_DATA DISABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_LOC DISABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_PRO DISABLE;

TRUNCATE TABLE TB_FATO_VENDA;

ALTER TABLE TB_FATO_VENDA ADD (VL_VENDA_TOTAL NUMBER );
ALTER TABLE TB_FATO_VENDA RENAME COLUMN VL_VENDA TO VL_VENDA_UNI;

INSERT INTO TB_FATO_VENDA (SK_CLIENTE,
                           SK_PRODUTO,
                           SK_LOCALIDADE,
                           SK_DATA,
                           VL_VENDA_UNI,
                           QTD_VENDA, 
                           VL_VENDA_TOTAL,
                           DATA_CARGA)
SELECT coalesce(B.SK_CLIENTE, -1) as SK_CLIENTE, 
       coalesce(C.SK_PRODUTO, -1) as SK_PRODUTO, 
       coalesce(D.SK_LOCALIDADE, -1) as SK_LOCALIDADE,
       TO_NUMBER(TO_CHAR(DATA_VENDA,'yyyymmdd'), '99999999') as SK_DATA,
       C.PRECO_UNITARIO as VL_VENDA_UNI,
       A.QUANTIDADE as QTD_VENDA,
       (C.PRECO_UNITARIO * A.QUANTIDADE) as VL_VENDA_TOTAL,
       CURRENT_DATE
FROM STAREA.ST_VENDA A LEFT JOIN TB_DIM_CLIENTE B 
  ON A.ID_CLIENTE = B.NK_ID_CLIENTE
  LEFT JOIN TB_DIM_PRODUTO C 
  ON A.ID_PRODUTO = C.NK_ID_PRODUTO
  LEFT JOIN TB_DIM_LOCALIDADE D
  ON A.ID_LOCALIDADE = D.NK_ID_LOCALIDADE;
COMMIT;

ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_CLIENTE ENABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_DATA ENABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_LOC ENABLE;
ALTER TABLE TB_FATO_VENDA MODIFY CONSTRAINT TB_FATO_VENDA_FK_PRO ENABLE;

SELECT
   D.NM_CATEGORIA_PAI as Categoria_Pai,
   D.NM_CATEGORIA_PRODUTO as Categoria,
   B.NM_MES as Mes,
   B.NR_ANO as Ano,
   SUM(A.QTD_VENDA) as QTD_VENDA_TOTAL,
   SUM(A.VL_VENDA_TOTAL) as VL_VENDA_TOTAL
 FROM TB_FATO_VENDA A
 INNER JOIN TB_DIM_TEMPO B      ON A.SK_DATA = B.SK_DATA
 INNER JOIN TB_DIM_CLIENTE C    ON A.SK_CLIENTE = C.SK_CLIENTE
 INNER JOIN TB_DIM_PRODUTO D    ON A.SK_PRODUTO = D.SK_PRODUTO
 INNER JOIN TB_DIM_LOCALIDADE E ON A.SK_LOCALIDADE = E.SK_LOCALIDADE
 GROUP BY D.NM_CATEGORIA_PAI, D.NM_CATEGORIA_PRODUTO, B.NR_ANO, B.NM_MES
 ORDER BY SUM(A.VL_VENDA_TOTAL) DESC;
 

